// TEMPORARY DATA

export let role = "admin";

export const teachersData = [

  {
    id: 1,
    name: "Chong Kwee Leng",
    desc: "Adjunct Lecturer",
    email: "chong_kwee@leng.np.edu.sg",
    phone: "9147 6283",
    subjects: ["CACM", " Computing Maths"],
    classes: ["T01", " T02", " T03"],
  },
  {
    id: 2,
    name: "Chong Zi Jie",
    desc: "Senior Lecturer",
    email: "chong_zi@jie.np.edu.sg",
    phone: "8324 7690",
    subjects: ["Applied Microbiology", " Biochemistry"],
    classes: ["T33", " T36", " T38"],
  },
  {
    id: 3,
    name: "Evelyn Tan",
    desc: "Senior Lecturer",
    email: "evelyn@tan.np.edu.sg",
    phone: "9834 5267",
    subjects: ["Economics", " Global Business"],
    classes: ["T01", " T03", " T21"],
  },
  {
    id: 4,
    name: "Jasmine Lim",
    desc: "SR Academic Fellow",
    email: "jasmine@lim.np.edu.sg",
    phone: "8437 1056",
    subjects: ["Building Technology", " Events Management"],
    classes: ["T51", " T06", " T12"],
  },
  {
    id: 5,
    name: "Marcus Lee",
    desc: "Senior Manager",
    email: "marcus@lee.np.edu.sg",
    phone: "8997 8423",
    subjects: ["Business Communication", " Business Law"],
    classes: ["T01", " T02", " T34"],
 },
 {
  id: 6,
  name: "Ng Zhen Yang",
  desc: "Senior Lecturer",
  email: "ng_zhen@yang.np.edu.sg",
  phone: "9015 2784",
  subjects: ["Clinical Practice", " Human Biosciences"],
  classes: ["T13", " T28", " T10"],
 },
 {
  id: 7,
  name: "Sandeep Singh",
  desc: "Senior Lecturer",
  email: "sandeep@singh.np.edu.sg",
  phone: "9271 4568",
  subjects: ["Engineering & Sustainability", " Offshore Wind"],
  classes: ["T03", " T25", " T08"],
 },
 {
  id: 8,
  name: "Siti Nur Aisyah",
  desc: "Senior Lecturer",
  email: "siti_nur@aisyah.np.edu.sg",
  phone: "8912 7654",
  subjects: ["Child Development", " Early Numeracy"],
  classes: ["T02", " T09", " T11"],
},
{
 id: 9,
 name: "Teo Jin Wei",
 desc: "Senior Manger",
 email: "teo_jin@wei.np.edu.sg",
 phone: "8765 4321",
 subjects: ["Multicam Production", " Multiplatform Journalism"],
 classes: ["T13", " T14", " T17"],
},
{
 id: 10,
 name: "Zheng Wei Liang",
 desc: "Adjunct Lecturer",
 email: "zheng_wei@liang.np.edu.sg",
 phone: "9586 3712",
 subjects: ["Database"],
 classes: ["T04", " T05", " T32"],
},
];

export const subjectsData = [
  {
    id: 1,
    name: "Designing User Experience",
    teachers: ["Henry Soh"],
    desc: "Senior Lecturer",
    email: "henry_soh@np.edu.sg",
    phone: "9672 5901",
    subjects: ["Designing User Experience", " Fundamentals for IT Professionals"],
    classes: ["T04", " T05", " T32"],
  },
  {
    id: 2,
    name: "Full Stack Development",
    teachers: ["Tan Jia Wei"],
    desc: "Senior Lecturer",
    email: "tan_jia_wei@np.edu.sg",
    phone: "8790 6573",
    subjects: ["Full Stack Development"],
    classes: ["T08", " T05"],
  },
  {
    id: 3,
    name: "Fundamentals for IT Professionals",
    teachers: ["Henry Soh"],
    desc: "Senior Lecturer",
    email: "henry_soh@np.edu.sg",
    phone: "9672 5901",
    subjects: ["Designing User Experience", " Fundamentals for IT Professionals"],
    classes: ["T04", " T05", " T32"],
  },
  {
    id: 4,
    name: "Modern Artifical Intelligence",
    teachers: ["Jeremy Lim"],
    desc: "Senior Academic Fellow",
    email: "jeremy_lim@np.edu.sg",
    phone: "9123 4567",
    subjects: ["Modern Artifical Intelligence", " Machine Learning"],
    classes: ["T02", " T05", " T15"],
  },
  {
    id: 5,
    name: "Machine Learning",
    teachers: ["Jeremy Lim"],
    desc: "Senior Academic Fellow",
    email: "jeremy_lim@np.edu.sg",
    phone: "9123 4567",
    subjects: ["Modern Artifical Intelligence", " Machine Learning"],
    classes: ["T02", " T05", " T15"],
  },
  {
    id: 6,
    name: "Deep Learning",
    teachers: ["Lee Jia En"],
    desc: "Senior Lecturer",
    email: "lee_jia_en@np.edu.sg",
    phone: "9234 5678",
    subjects: ["Deep Learning"],
    classes: ["T01", " T03", " T07"],
  },
];

export const classesData = [
  {
    id: 1,
    name: "1A",
    capacity: 20,
    grade: 1,
    supervisor: "Joseph Padilla",
  },
  {
    id: 2,
    name: "2B",
    capacity: 22,
    grade: 2,
    supervisor: "Blake Joseph",
  },
  {
    id: 3,
    name: "3C",
    capacity: 20,
    grade: 3,
    supervisor: "Tom Bennett",
  },
  {
    id: 4,
    name: "4B",
    capacity: 18,
    grade: 4,
    supervisor: "Aaron Collins",
  },
  {
    id: 5,
    name: "5A",
    capacity: 16,
    grade: 5,
    supervisor: "Iva Frank",
  },
  {
    id: 5,
    name: "5B",
    capacity: 20,
    grade: 5,
    supervisor: "Leila Santos",
  },
  {
    id: 7,
    name: "7A",
    capacity: 18,
    grade: 7,
    supervisor: "Carrie Walton",
  },
  {
    id: 8,
    name: "6B",
    capacity: 22,
    grade: 6,
    supervisor: "Christopher Butler",
  },
  {
    id: 9,
    name: "6C",
    capacity: 18,
    grade: 6,
    supervisor: "Marc Miller",
  },
  {
    id: 10,
    name: "6D",
    capacity: 20,
    grade: 6,
    supervisor: "Ophelia Marsh",
  },
];

export const lessonsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Tommy Wise",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Rhoda Frank",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Della Dunn",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Bruce Rodriguez",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Birdie Butler",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Bettie Oliver",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Herman Howard",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Lucinda Thomas",
  },
  {
    id: 9,
    subject: "Physics",
    class: "6C",
    teacher: "Ronald Roberts",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "4B",
    teacher: "Julia Pittman",
  },
];

export const examsData = [
  {
    id: 1,
    subject: "Modern Artifical Intelligence",
    class: "T05",
    date: "2025-01-02",
    time: "0900 - 1100",
  },
  {
    id: 2,
    subject: "Machine Learning",
    class: "T05",
    date: "2025-01-03",
    time: "1000 - 1200",
  },
  {
    id: 3,
    subject: "Deep Learning",
    class: "T05",
    date: "2025-01-04",
    time: "0830 - 1100",
  },
];

export const assignmentsData = [
  {
    id: 1,
    subject: "Designing User Experience",
    class: "T02",
    assignment: "Assignment 2a",
    dueDate: "2025-01-01",
  },
  {
    id: 2,
    subject: "Full Stack Development",
    class: "T05",
    assignment: "Web Development Project",
    dueDate: "2025-01-01",
  },
  {
    id: 3,
    subject: "Fundamentals for IT Professionals",
    class: "T05",
    assignment: "Assignment 2b Email Writing",
    dueDate: "2025-01-02",
  },
  {
    id: 4,
    subject: "Machine Learning",
    class: "T05",
    assignment: "Final Assignment",
    dueDate: "2025-01-02",
  },
  {
    id: 5,
    subject: "Modern Artifical Intelligence",
    class: "T05",
    assignment: "Research Paper",
    dueDate: "2025-01-03",
  },
  {
    id: 6,
    subject: "Designing User Experience",
    class: "T05",
    assignment: "Feedback Fruits Peer Evaluation",
    dueDate: "2025-01-04",
  },
  {
    id: 7,
    subject: "Deep Learning",
    class: "T05",
    assignment: "Final Project",
    dueDate: "2025-01-05",
  },
];

export const resultsData = [
  {
    id: 1,
    subject: "Designing User Experience",
    class: "T07",
    teacher: "Henry Soh",
    date: "2024-12-18",
    type: "exam",
    score: "A",
  },
  {
    id: 2,
    subject: "Full Stack Development",
    class: "T07",
    teacher: "Tan Jia Wei",
    date: "2024-12-19",
    type: "exam",
    score: "A",
  },
  {
    id: 3,
    subject: "Fundamentals for IT Professionals",
    class: "T07",
    teacher: "Henry Soh",
    date: "2024-12-20",
    type: "exam",
    score: "B+",
  },
  {
    id: 4,
    subject: "Modern Artifical Intelligence",
    class: "T01",
    teacher: "Jeremy Lim",
    date: "2024-12-22",
    type: "exam",
    score: "C",
  },
  {
    id: 5,
    subject: "Machine Learning",
    class: "T01",
    teacher: "Jeremy Lim",
    date: "2024-12-23",
    type: "exam",
    score: "C",
  },
  {
    id: 6,
    subject: "Deep Learning",
    class: "T14",
    teacher: "Lee Jia En",
    date: "2025-12-23",
    type: "exam",
    score: "D",
  },
];

export const eventsData = [
  {
    id: 1,
    title: "AI, Skills and Employment Talk",
    venue: "LT51D",
    date: "2025-01-29",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 2,
    title: "Navigating Your Tech Career: Internship Prep & Insights",
    venue: "LT51D",
    date: "2025-01-30",
    startTime: "11:00",
    endTime: "12:00",
  },
  {
    id: 3,
    title: "NP Careers Networking Fair",
    venue: "Atrium", 
    date: "2025-02-04",
    startTime: "09:00",
    endTime: "18:00",
  },
  {
    id: 4,
    title: "Bites & Vibes Fest",
    venue: "Atrium",
    date: "2025-02-06",
    startTime: "10:00",
    endTime: "18:00",
  },
  {
    id: 5,
    title: "Zoom Work Transformation Summit",
    venue: "Teams",
    date: "2025-02-07",
    startTime: "08:00",
    endTime: "11:00",
  },
  {
    id: 6,
    title: "NP CCA Fiesta 2025",
    venue: "Outside Food Club",
    date: "2025-04-08",
    startTime: "09:00",
    endTime: "18:00",
  },
  {
    id: 7,
    title: "Trailblazer Leadership Summit",
    venue: "NPYA",
    date: "2025-04-13",
    startTime: "10:00",
    endTime: "12:00",
  },
  {
    id: 8,
    title: "Walk for Rice",
    venue: "School Field",
    date: "2025-04-20",
    startTime: "17:00",
    endTime: "19:00",
  },
  {
    id: 9,
    title: "Oracle Cloud Day",
    venue: "Oracle Office",
    date: "2025-05-22",
    startTime: "10:00",
    endTime: "13:00",
  },
  {
    id: 10,
    title: "Let's Swing",
    venue: "SOTA Concert Hall",
    date: "2025-05-25",
    startTime: "19:30",
    endTime: "21:30",
  },
];

export const announcementsData = [
  {
    id: 1,
    module: "Designing User Experience",
    title: "Updates to Final Assignment",
    class: "T07",
    date: "2025-01-06",
    details: "The final assignment has been updated. Please refer to the updated guidelines on the course website.",
  },
  {
    id: 2,
    module: "Designing User Experience",
    title: "Final Assignment Released",
    class: "T07",
    date: "2025-01-05",
    details: "The final assignment has been released. Please refer to the guidelines on the course website.",
  },
  {
    id: 3,
    module: "Full Stack Development",
    title: "Practical Exercise 7 Due on Sunday",
    class: "T07",
    date: "2025-01-05",
    details: "Practical Exercise 7 is due on Sunday. Please submit your work on time.",
  },
  {
    id: 4,
    module: "Full Stack Development",
    title: "Week 13 Materials Available",
    class: "T07",
    date: "2025-01-04",
    details: "Week 13 materials are now available on the course website. Please review them before the next class.",
  },
  {
    id: 5,
    module: "Fundamentals for IT Professionals",
    title: "Submission of Assessment 1 Updated",
    class: "T07",
    date: "2025-01-03",
    details: "The submission deadline for Assessment 1 has been extended. Please refer to the updated guidelines on the course website.",
  },
  {
    id: 6,
    module: "Fundamentals for IT Professionals",
    title: "Submission of Assessment 1 Released",
    class: "T07",
    date: "2025-01-03",
    details: "The submission guidelines for Assessment 1 have been released. Please refer to the guidelines on the course website.",
  },
  {
    id: 7,
    module: "Modern Artifical Intelligence",
    title: "Main Quiz on Wednesday",
    class: "T01",
    date: "2025-01-02",
    details: `Hi MAI Learners
1) The Main Quiz is scheduled on 5 February 2025, Wednesday starts at 10am SGT. 
2) The duration of the quiz is set to 90 mins.
3) Students are to be seated by 0940am at NP venue: LT79 
4) There will be 65 Multiple Choice Questions.`

  },
  {
    id: 8,
    module: "Machine Learning",
    title: "Quiz 1 Grade Released",
    class: "T01",
    date: "2025-01-01",
    details: "The grades for Quiz 1 have been released. Please check your grade on the course website.",
  },
  {
    id: 9,
    module: "Machine Learning",
    title: "Quiz 1 Due on 1 Jan 2025",
    class: "T01",
    date: "2024-12-20",
    details: "Quiz 1 is due on 1 Jan 2025. Please complete the quiz before the deadline.",
  },
  {
    id: 10,
    module: "Deep Learning",
    title: "Week 7 Materials Available",
    class: "T14",
    date: "2024-11-17",
    details: "Week 7 materials are now available on the course website. Please review them before the next class.",
  },
];


// CHANGE THE DATES OF THE EVENTS TO THE CURRENT DATE TO SEE THE EVENTS ON THE CALENDAR
// new Date(year, month - 1, day, 24-hour, minutes)
export const calendarEvents = [
  {
    title: "Designing User Experience",
    allDay: false,
    start: new Date(2025, 1, 3, 8, 0),
    end: new Date(2025, 1, 3, 8, 45),
  },
  {
    title: "Full Stack Development",
    allDay: false,
    start: new Date(2025, 1, 3, 9, 0),
    end: new Date(2025, 1, 3, 9, 45),
  },
  {
    title: "Fundamentals for IT Professionals",
    allDay: false,
    start: new Date(2025, 1, 4, 10, 0),
    end: new Date(2025, 1, 4, 10, 45),
  },
  {
    title: "Modern Artifical Intelligence",
    allDay: false,
    start: new Date(2025, 1, 4, 11, 0),
    end: new Date(2025, 1, 4, 11, 45),
  },
  {
    title: "Machine Learning",
    allDay: false,
    start: new Date(2025, 1, 6, 13, 0),
    end: new Date(2025, 1, 6, 13, 45),
  },
  {
    title: "Deep Learning",
    allDay: false,
    start: new Date(2025, 1, 7, 10, 0),
    end: new Date(2025, 1, 7, 12, 45),
  },
];