export const words = [
    "Academic Calendar",
    "Academic Advising",
    "Academic Conferences",
    "Academic Integrity",
    "Academic Support",
    "Admissions",
    "After-School Programs",
    "Alumni Services",
    "Application Deadlines",
    "Campus Life",
    "Campus Map",
    "Career Services",
    "Class Schedules",
    "Classroom Management",
    "College Admissions",
    "Community Outreach",
    "Community Service",
    "Course Catalog",
    "Course Registration",
    "Cultural Awareness",
    "Cultural Programs",
    "Cybersecurity in Education",
    "Digital Literacy",
    "Distance Education",
    "Distance Learning",
    "Educational Partnerships",
    "Educational Programs",
    "Educational Resources",
    "Education Policies",
    "Enrollment",
    "Events Calendar",
    "Extracurricular Activities",
    "Faculty Development",
    "Faculty Directory",
    "Financial Aid",
    "Grades",
    "Graduation Requirements",
    "Health Services",
    "Higher Education",
    "Inclusive Education",
    "International Students",
    "Internship Opportunities",
    "Language Programs",
    "Learning Disabilities",
    "Learning Management Systems",
    "Library Services",
    "Mental Health Services",
    "Online Courses",
    "Online Learning",
    "Parental Involvement",
    "Parenting Resources",
    "Peer Tutoring",
    "Professional Development",
    "Program Accreditations",
    "Public Schools",
    "Research Grants",
    "Research Opportunities",
    "School Accreditation",
    "School Directory",
    "School Holidays",
    "School Locations",
    "School Rankings",
    "School Ratings",
    "School Safety",
    "Schools",
    "Scholarships",
    "Special Education",
    "Student Assessment",
    "Student Code of Conduct",
    "Student Counseling",
    "Student Engagement",
    "Student Housing",
    "Student Registration",
    "Student Services",
    "Student Support",
    "Student Well-being",
    "Study Abroad",
    "Study Groups",
    "Study Skills",
    "Summer Programs",
    "Teacher Certification",
    "Teacher Evaluations",
    "Teacher Resources",
    "Teacher Training",
    "Test Preparation",
    "Thesis Opportunities",
    "Tuition Fees",
    "Transportation Services",
    "Transcript Requests",
    "Vocational Training",
    "Work-Study Programs"
];
