// TEMPORARY DATA

export let role = "admin";

export const teachersData = [
  {
    id: 1,
    name: "Evelyn Tan",
    desc: "Senior Lecturer",
    email: "evelyn@tan.np.edu.sg",
    phone: "9834 5267",
    subjects: ["Economics", " Global Business"],
    classes: ["T01", " T03", " T21"],
  },
  {
    id: 2,
    name: "Marcus Lee",
    desc: "Senior Manager",
    email: "marcus@lee.np.edu.sg",
    phone: "8997 8423",
    subjects: ["Business Communication", " Business Law"],
    classes: ["T01", " T02", " T34"],
  },
  {
    id: 3,
    name: "Jasmine Lim",
    desc: "SR Academic Fellow",
    email: "jasmine@lim.np.edu.sg",
    phone: "8437 1056",
    subjects: ["Building Technology", " Events Management"],
    classes: ["T51", " T06", " T12"],
  },
  {
    id: 4,
    name: "Zheng Wei Liang",
    desc: "Adjunct Lecturer",
    email: "zheng_wei@liang.np.edu.sg",
    phone: "9586 3712",
    subjects: ["Database"],
    classes: ["T04", " T05", " T32"],
  },
  {
    id: 5,
    name: "Siti Nur Aisyah",
    desc: "Senior Lecturer",
    email: "siti_nur@aisyah.np.edu.sg",
    phone: "8912 7654",
    subjects: ["Child Development", " Early Numeracy"],
    classes: ["T02", " T09", " T11"],
  },
  {
    id: 6,
    name: "Sandeep Singh",
    desc: "Senior Lecturer",
    email: "sandeep@singh.np.edu.sg",
    phone: "9271 4568",
    subjects: ["Engineering & Sustainability", " Offshore Wind"],
    classes: ["T03", " T25", " T08"],
  },
  {
    id: 7,
    name: "Teo Jin Wei",
    desc: "Senior Manger",
    email: "teo_jin@wei.np.edu.sg",
    phone: "8765 4321",
    subjects: ["Multicam Production", " Multiplatform Journalism"],
    classes: ["T13", " T14", " T17"],
  },
  {
    id: 8,
    name: "Chong Kwee Leng",
    desc: "Adjunct Lecturer",
    email: "chong_kwee@leng.np.edu.sg",
    phone: "9147 6283",
    subjects: ["CACM", " Computing Maths"],
    classes: ["T01", " T02", " T03"],
  },
  {
    id: 9,
    name: "Chong Zi Jie",
    desc: "Senior Lecturer",
    email: "chong_zi@jie.np.edu.sg",
    phone: "8324 7690",
    subjects: ["Applied Microbiology", " Biochemistry"],
    classes: ["T33", " T36", " T38"],
  },
  {
    id: 10,
    name: "Ng Zhen Yang",
    desc: "Senior Lecturer",
    email: "ng_zhen@yang.np.edu.sg",
    phone: "9015 2784",
    subjects: ["Clinical Practice", " Human Biosciences"],
    classes: ["T13", " T28", " T10"],
  },
];

export const subjectsData = [
  {
    id: 1,
    name: "Math",
    teachers: ["Alice Phelps", "Russell Davidson"],
  },
  {
    id: 2,
    name: "English",
    teachers: ["Manuel Becker", "Eddie Chavez"],
  },
  {
    id: 3,
    name: "Physics",
    teachers: ["Lola Newman", "Darrell Delgado"],
  },
  {
    id: 4,
    name: "Chemistry",
    teachers: ["Nathan Kelly", "Benjamin Snyder"],
  },
  {
    id: 5,
    name: "Biology",
    teachers: ["Alma Benson", "Lina Collier"],
  },
  {
    id: 6,
    name: "History",
    teachers: ["Hannah Bowman", "Betty Obrien"],
  },
  {
    id: 7,
    name: "Geography",
    teachers: ["Lora French", "Sue Brady"],
  },
  {
    id: 8,
    name: "Art",
    teachers: ["Harriet Alvarado", "Mayme Keller"],
  },
  {
    id: 9,
    name: "Music",
    teachers: ["Gertrude Roy", "Rosa Singleton"],
  },
  {
    id: 10,
    name: "Literature",
    teachers: ["Effie Lynch", "Brett Flowers"],
  },
];

export const classesData = [
  {
    id: 1,
    name: "1A",
    capacity: 20,
    grade: 1,
    supervisor: "Joseph Padilla",
  },
  {
    id: 2,
    name: "2B",
    capacity: 22,
    grade: 2,
    supervisor: "Blake Joseph",
  },
  {
    id: 3,
    name: "3C",
    capacity: 20,
    grade: 3,
    supervisor: "Tom Bennett",
  },
  {
    id: 4,
    name: "4B",
    capacity: 18,
    grade: 4,
    supervisor: "Aaron Collins",
  },
  {
    id: 5,
    name: "5A",
    capacity: 16,
    grade: 5,
    supervisor: "Iva Frank",
  },
  {
    id: 5,
    name: "5B",
    capacity: 20,
    grade: 5,
    supervisor: "Leila Santos",
  },
  {
    id: 7,
    name: "7A",
    capacity: 18,
    grade: 7,
    supervisor: "Carrie Walton",
  },
  {
    id: 8,
    name: "6B",
    capacity: 22,
    grade: 6,
    supervisor: "Christopher Butler",
  },
  {
    id: 9,
    name: "6C",
    capacity: 18,
    grade: 6,
    supervisor: "Marc Miller",
  },
  {
    id: 10,
    name: "6D",
    capacity: 20,
    grade: 6,
    supervisor: "Ophelia Marsh",
  },
];

export const lessonsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Tommy Wise",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Rhoda Frank",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Della Dunn",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Bruce Rodriguez",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Birdie Butler",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Bettie Oliver",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Herman Howard",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Lucinda Thomas",
  },
  {
    id: 9,
    subject: "Physics",
    class: "6C",
    teacher: "Ronald Roberts",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "4B",
    teacher: "Julia Pittman",
  },
];

export const examsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Martha Morris",
    date: "2025-01-01",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Randall Garcia",
    date: "2025-01-01",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Myrtie Scott",
    date: "2025-01-01",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Alvin Swanson",
    date: "2025-01-01",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Mabelle Wallace",
    date: "2025-01-01",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Dale Thompson",
    date: "2025-01-01",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Allie Conner",
    date: "2025-01-01",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Hunter Fuller",
    date: "2025-01-01",
  },
  {
    id: 9,
    subject: "Physics",
    class: "7A",
    teacher: "Lois Lindsey",
    date: "2025-01-01",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "8A",
    teacher: "Vera Soto",
    date: "2025-01-01",
  },
];

export const assignmentsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Anthony Boone",
    dueDate: "2025-01-01",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Clifford Bowen",
    dueDate: "2025-01-01",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Catherine Malone",
    dueDate: "2025-01-01",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Willie Medina",
    dueDate: "2025-01-01",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Jose Ruiz",
    dueDate: "2025-01-01",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Katharine Owens",
    dueDate: "2025-01-01",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Shawn Norman",
    dueDate: "2025-01-01",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Don Holloway",
    dueDate: "2025-01-01",
  },
  {
    id: 9,
    subject: "Physics",
    class: "7A",
    teacher: "Franklin Gregory",
    dueDate: "2025-01-01",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "8A",
    teacher: "Danny Nguyen",
    dueDate: "2025-01-01",
  },
];

export const resultsData = [
  {
    id: 1,
    subject: "Designing User Experience",
    class: "T07",
    teacher: "Henry Soh",
    date: "2024-12-18",
    type: "exam",
    score: "A",
  },
  {
    id: 2,
    subject: "Full Stack Development",
    class: "T07",
    teacher: "Tan Jia Wei",
    date: "2024-12-19",
    type: "exam",
    score: "A",
  },
  {
    id: 3,
    subject: "Fundamentals for IT Professionals",
    class: "T07",
    teacher: "Henry Soh",
    date: "2024-12-20",
    type: "exam",
    score: "B+",
  },
  {
    id: 4,
    subject: "Modern Artifical Intelligence",
    class: "T01",
    teacher: "Jeremy Lim",
    date: "2024-12-22",
    type: "exam",
    score: "C",
  },
  {
    id: 5,
    subject: "Machine Learning",
    class: "T01",
    teacher: "Jeremy Lim",
    date: "2024-12-23",
    type: "exam",
    score: "C",
  },
  {
    id: 6,
    subject: "Deep Learning",
    class: "T14",
    teacher: "Lee Jia En",
    date: "2025-12-23",
    type: "exam",
    score: "D",
  },
];

export const eventsData = [
  {
    id: 1,
    title: "AI, Skills and Employment Talk",
    venue: "LT51D",
    date: "2025-01-02",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 2,
    title: "Navigating Your Tech Career: Internship Prep & Insights",
    venue: "LT51D",
    date: "2025-01-02",
    startTime: "11:00",
    endTime: "12:00",
  },
  {
    id: 3,
    title: "NP Careers Networking Fair",
    venue: "Atrium", 
    date: "2025-01-04",
    startTime: "09:00",
    endTime: "18:00",
  },
  {
    id: 4,
    title: "Bites & Vibes Fest",
    venue: "Atrium",
    date: "2025-01-06",
    startTime: "10:00",
    endTime: "18:00",
  },
  {
    id: 5,
    title: "Zoom Work Transformation Summit",
    venue: "Teams",
    date: "2025-01-07",
    startTime: "08:00",
    endTime: "11:00",
  },
  {
    id: 6,
    title: "NP Open House 2025",
    venue: "Outside Food Club",
    date: "2025-01-08",
    startTime: "09:00",
    endTime: "18:00",
  },
  {
    id: 7,
    title: "Trailblazer Leadership Summit",
    venue: "NPYA",
    date: "2025-01-13",
    startTime: "10:00",
    endTime: "12:00",
  },
  {
    id: 8,
    title: "Walk for Rice",
    venue: "School Field",
    date: "2025-01-20",
    startTime: "17:00",
    endTime: "19:00",
  },
  {
    id: 9,
    title: "Oracle Cloud Day",
    venue: "Oracle Office",
    date: "2025-01-22",
    startTime: "10:00",
    endTime: "13:00",
  },
  {
    id: 10,
    title: "Let's Swing",
    venue: "SOTA Concert Hall",
    date: "2025-01-25",
    startTime: "19:30",
    endTime: "21:30",
  },
];

export const announcementsData = [
  {
    id: 1,
    module: "Designing User Experience",
    title: "Updates to Final Assignment",
    class: "T07",
    date: "2025-01-06",
  },
  {
    id: 2,
    module: "Designing User Experience",
    title: "Final Assignment Released",
    class: "T07",
    date: "2025-01-05",
  },
  {
    id: 3,
    module: "Full Stack Development",
    title: "Practical Exercise 7 Due on Sunday",
    class: "T07",
    date: "2025-01-05",
  },
  {
    id: 4,
    module: "Full Stack Development",
    title: "Week 13 Materials Available",
    class: "T07",
    date: "2025-01-04",
  },
  {
    id: 5,
    module: "Fundamentals for IT Professionals",
    title: "Submission of Assessment 1 Updated",
    class: "T07",
    date: "2025-01-03",
  },
  {
    id: 6,
    module: "Fundamentals for IT Professionals",
    title: "Submission of Assessment 1 Released",
    class: "T07",
    date: "2025-01-03",
  },
  {
    id: 7,
    module: "Modern Artifical Intelligence",
    title: "Gentle Reminder for Assignment 2",
    class: "T01",
    date: "2025-01-02",
  },
  {
    id: 8,
    module: "Machine Learning",
    title: "Quiz 1 Grade Released",
    class: "T01",
    date: "2025-01-01",
  },
  {
    id: 9,
    module: "Machine Learning",
    title: "Quiz 1 Due on 1 Jan 2025",
    class: "T01",
    date: "2024-12-20",
  },
  {
    id: 10,
    module: "Deep Learning",
    title: "Week 7 Materials Available",
    class: "T14",
    date: "2024-11-17",
  },
];


// CHANGE THE DATES OF THE EVENTS TO THE CURRENT DATE TO SEE THE EVENTS ON THE CALENDAR
// new Date(year, month - 1, day, 24-hour, minutes)
export const calendarEvents = [
  {
    title: "Math",
    allDay: false,
    start: new Date(2025, 0, 6, 8, 0),
    end: new Date(2025, 0, 6, 8, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2025, 0, 7, 9, 0),
    end: new Date(2025, 0, 7, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2025, 0, 6, 10, 0),
    end: new Date(2025, 0, 6, 10, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2025, 0, 8, 11, 0),
    end: new Date(2025, 0, 8, 11, 45),
  },
  {
    title: "Chemistry",
    allDay: false,
    start: new Date(2025, 0, 9, 13, 0),
    end: new Date(2025, 0, 9, 13, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2025, 0, 7, 14, 0),
    end: new Date(2025, 0, 7, 14, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2025, 0, 10, 9, 0),
    end: new Date(2025, 0, 10, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2025, 0, 10, 10, 0),
    end: new Date(2025, 0, 10, 10, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2025, 0, 8, 11, 0),
    end: new Date(2025, 0, 8, 11, 45),
  }
];